# Generated by Django 5.0.4 on 2024-04-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('creditos', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Curos',
            },
        ),
    ]
